name: ${project.name}
version: ${project.version}
description: ${project.description}
author: PureGero, jjkay03

main: com.jjkay03.foliawarp.FoliaWarp
api-version: 1.20
folia-supported: true

commands:
  warp:
    description: Warp to a location
    permission: warps.warp
  setwarp:
    description: Set a warp location
    permission: warps.setwarp
  delwarp:
    description: Delete a warp location
    permission: warps.setwarp

permissions:
    warps.warp:
        default: op
    warps.setwarp:
        default: op